version: '3'

services:
  server1:
    build: ./server1
    networks:
      - app_network

  server2:
    build: ./server2
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - app_network

  client:
    build: ./client
    environment:
      - DISPLAY=:0
      - GDK_BACKEND=x11  # Принудительное использование X11
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
